theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
format = "{average}C"
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "load"
interval = 2
format = "{1m}"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = true
speed_up = false
interval = 3

[[block]]
block = "battery"
interval = 10
show = "percentage"
device = "BAT0"

[[block]]
block = "time"
interval = 1
format = "wk%U %a %d/%m %R:%S"

